postgres:
  image: postgres
  volumes:
    - ./data/postgres:/var/lib/postgresql/data
  environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
uwsgi:
  build: .
  links:
    - postgres
    - smtp
  command: ./uwsgi.sh
  volumes:
    - ./code/project:/project
    - /static
    - ./data/media:/media
nginx:
  build: ./nginx
  links:
    - uwsgi
  volumes_from:
    - uwsgi
  ports:
    - "8000:80"
smtp:
  image: namshi/smtp
